
- name: start firewall service
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Add apache service to firewall
  ansible.posix.firewalld:
    service: '{{ item }}'
    state: enabled
    immediate: true
    permanent: true
  loop:
    - http
    - https

- name: Add ports to firewall
  ansible.posix.firewalld:
    port: '{{ item }}'
    state: enabled
    immediate: true
    permanent: true
  loop:
    - 80/tcp
    - 443/tcp
