---
# tasks file for clean_setup_fstab
#
- name: remove entries from fstab file
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: "^{{ item }}"
    line: ""
    backup: true
  tags: clean_fstab
  loop:
    - '{{ diego_ip }}'
    - '{{ goku_ip }}'
