- name: install unzip
  ansible.builtin.package:
    name: unzip
 
- name: install terraform
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
