---
# tasks file for setup_exports
#
- name: Add paths to exports file
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "{{ nfs_home_dir }}   {{ control_host_ip }}(rw,sync,no_root_squash)"
    backup: true
  notify: restart nfs server
