---
# tasks file for clean_setup_exports
#
- name: Remove entries from exports file
  ansible.builtin.lineinfile:
    path: /etc/exports
    regexp: "^{{ nfs_home_dir }}"
    line: ""
    backup: false
