---
# tasks file for autofs_user_add
#
- name: Create user group accounts
  ansible.builtin.group:
    name: '{{ item.name }}'
    state: present
    gid: '{{ item.id }}'
  loop: '{{ autofs_users }}'

- name: Create users without creating home directories for autofs
  ansible.builtin.user:
    name: '{{ item.name }}'
    state: present
    uid: '{{ item.id }}'
    group: '{{ item.name }}'
    home: '{{ item.home_dir }}'
    create_home: false
    expires: -1
  loop: '{{ autofs_users }}'
